apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "locatic.fullname" . }}-config
  labels:
    {{- include "locatic.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.config.aspnetcoreEnvironment | quote }}
  ASPNETCORE_URLS: {{ .Values.config.aspnetcoreUrls | quote }}
  ConnectionStrings__DefaultConnection: "Data Source={{ .Values.sqlite.mountPath }}/{{ .Values.sqlite.fileName }}"
